config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'
  post 'change_location' => 'home#change_location'

end

app/models/food.rb
# == Schema Information
#
# Table name: foods
#
#  id         :integer          not null, primary key
#  food_type  :integer
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  meal_id    :integer
#

class Food < ActiveRecord::Base
	belongs_to :meal, inverse_of: :foods
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id         :integer          not null, primary key
#  time       :datetime
#  location   :integer
#  created_at :datetime
#  updated_at :datetime
#  meal_type  :integer
#

require 'open-uri'
require 'nokogiri'

class Meal < ActiveRecord::Base
	include HomeHelper
	# if updating enum, make sure to update locations_for_display below
	enum location: {selleck: 23, cpn: 24, hss:20, abel:22, east_cafe:101, east_deli:106}
	enum meal_type: [:breakfast, :lunch, :dinner]
	has_many :foods, inverse_of: :meal

def getFoodsForMeal(hall,type)
	doc = Nokogiri::HTML(open("http://menu.unl.edu/default.aspx?gComplex=#{hall}"))	
	foods = [] 
	queryString = "#cphMain_pnl#{type.capitalize}Items .MenuItem"
	doc.css(queryString).each do | item |
		unless item.content.blank?
			food = Food.new
			food.food_type = type
			food.name = clean_food_name(item.content)
			foods.push food
		end
	end
	self.foods = foods
	self.save
end

def self.locations_for_display
	{"Selleck" => 23, "CPN" => 24, "HSS" => 20, "Abel/Sandoz" => 22, "East Campus Cafe" => 101, "East Campus Deli" => 106}
end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
include HomeHelper

  def index(location = nil)
    @meal = get_meal
  end

  def change_location
    @meal = get_meal(params[:location])
    render partial: 'redraw_meal'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def clean_food_name(name)
		#	Vegetarian Symbols:	    * Vegan, + Lacto, - Ovo, = Lacto-Ovo
		# removing these now but they're actually important and mean things
		name.slice! '+'
		name.slice! '='

		# get rid of dashes at the end of name
		if name[name.length - 1] == '-'
			name = name[0..-2]
		end
		name	
	end

	def select_current_meal
		now = Time.current
		
		# for testing
		#now = Time.current.change(hour:15, min:30)
		current_meal = ""
		lunch_start = Time.current.change(hour:10, min:30)
		dinner_start = Time.current.change(hour:3, min:30)
		# no breakfast on weekends
		if !now.saturday? && !now.sunday? && now.minus_with_coercion(lunch_start) < 0
			current_meal = 'breakfast'
		elsif now.minus_with_coercion(dinner_start) < 0
			current_meal = 'lunch'
		else
			current_meal = 'dinner'
		end
		return current_meal
	end

	def get_meal(location = nil)
	 	current_meal = select_current_meal

	  	# I want to do:
	  	# where(meal_type: current_meal)
	  	# but it doesn't work - always sends 0 as meal_type. 
	  	# Would be nice to figure out why.
	  	location = Meal.locations['selleck'] if location.nil?

	  	m = Meal.send(current_meal).where("location = ?", location).where("created_at >= ?", Time.current.beginning_of_day).first

	  	if m.blank?
	  		m = Meal.new 
	  		m.meal_type = current_meal
	  		m.getFoodsForMeal(location, current_meal)
	  	end
	  	m
  	end

	# format for display
	def format_location_name(locations)
		locations.each { |loc| 
			loc.capitalize!

		}
	end
end

app/views/home/_meal_section.html.erb
	<ul>
		<% @meal.foods.each do |item| %>
		<li><%= item.name %></li>
		<% end %>
	</ul>
	<% if @meal.foods.blank? %>
	<h1> No information available. Are you sure this hall is open? </h1>
	<% end %>

app/views/home/_redraw_meal.js.erb
$('#meal_section').html("<%= j render partial: 'meal_section' %>");

app/views/home/index.html.erb
	<%= form_tag change_location_path(), remote: true do %>
		<%= select_tag "location", options_for_select(Meal.locations_for_display) %>
		<%= submit_tag "GOOOO" %>
	<% end %>
<div id="meal_section">
	<%= render partial: "meal_section" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>